# data_analysis/scripts/train_salary_model.py
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor # 示例模型，可以换成 XGBoost, LightGBM 等
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import joblib, json
from data_processing import load_and_clean_data, create_feature_transformer # 从同目录导入

MODELS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'models')

def train_model():
    print("Loading and cleaning data for training...")
    df = load_and_clean_data()
    if df.empty:
        print("No data to train on. Exiting.")
        return

    # 定义特征 (X) 和目标 (y)
    # 确保移除了所有形式的薪资列和非特征列
    potential_target_cols = ['avg_month_pay', 'low_month_pay', 'high_month_pay']
    cols_to_drop_for_X = [col for col in potential_target_cols if col in df.columns]
    # 也移除一些爬虫上下文或ID类，除非你认为它们是特征
    cols_to_drop_for_X.extend(['job_id', 'company_id', 'source_url', 
                               'publish_date', 'update_date', # 使用解析后的日期特征（如果添加）
                               'search_area_code', 'search_area_name', 'search_keyword', 
                               'search_category_code', 'search_industry_code'])
    # 移除原始的文本列，因为我们有 combined_text_features
    cols_to_drop_for_X.extend(['major_required', 'company_tags'])


    X = df.drop(columns=[col for col in cols_to_drop_for_X if col in df.columns])
    y = df['avg_month_pay']

    print(f"Shape of X before preprocessing: {X.shape}")
    print(f"Shape of y: {y.shape}")
    if X.empty or y.empty:
        print("Feature set X or target y is empty after dropping columns. Check column names.")
        return

    # 划分训练集和测试集
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    print(f"Training set size: {len(X_train)}, Test set size: {len(X_test)}")

    # 创建并拟合预处理器
    print("Creating and fitting preprocessor...")
    # 定义哪些列是类别型，哪些是数值型 (应与 data_processing.py 中的定义一致或作为参数传入)
    categorical_features = [col for col in ['job_catory', 'job_industry', 'area_code_name', 
                                            'company_scale', 'degree_name', 'company_property'] if col in X_train.columns]
    numerical_features = [col for col in ['head_count'] if col in X_train.columns and pd.api.types.is_numeric_dtype(X_train[col])]
    
    preprocessor, feature_names = create_feature_transformer(
        X_train.copy(), # 使用副本以避免修改原始X_train
        text_feature_col='combined_text_features', # 确保此列在X_train中
        categorical_cols=categorical_features,
        numerical_cols=numerical_features
    )

    if not preprocessor:
        print("Preprocessor creation failed. Cannot train model.")
        return

    print(f"Number of features after preprocessing: {len(feature_names)}")
    if not feature_names:
        print("Warning: No feature names generated by preprocessor.")

    # 转换训练数据和测试数据
    print("Transforming data with preprocessor...")
    X_train_processed = preprocessor.transform(X_train)
    X_test_processed = preprocessor.transform(X_test)
    
    print(f"Shape of X_train_processed: {X_train_processed.shape}")
    print(f"Shape of X_test_processed: {X_test_processed.shape}")


    # 训练模型 (示例：随机森林回归)
    print("Training RandomForestRegressor model...")
    model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1, max_depth=20, min_samples_split=10, min_samples_leaf=5)
    model.fit(X_train_processed, y_train)

    # 评估模型
    print("Evaluating model...")
    y_pred_train = model.predict(X_train_processed)
    y_pred_test = model.predict(X_test_processed)

    print("\n--- Model Evaluation ---")
    print(f"Train R^2: {r2_score(y_train, y_pred_train):.4f}")
    print(f"Test R^2: {r2_score(y_test, y_pred_test):.4f}")
    print(f"Train MAE: {mean_absolute_error(y_train, y_pred_train):.2f} K")
    print(f"Test MAE: {mean_absolute_error(y_test, y_pred_test):.2f} K")
    print(f"Train RMSE: {np.sqrt(mean_squared_error(y_train, y_pred_train)):.2f} K")
    print(f"Test RMSE: {np.sqrt(mean_squared_error(y_test, y_pred_test)):.2f} K")
    print("------------------------")

    # 保存模型和预处理器
    model_path = os.path.join(MODELS_DIR, 'salary_predictor_model.pkl')
    preprocessor_path = os.path.join(MODELS_DIR, 'salary_preprocessor.pkl')
    joblib.dump(model, model_path)
    joblib.dump(preprocessor, preprocessor_path) # 保存为 salary_preprocessor.pkl
    print(f"Model saved to {model_path}")
    print(f"Preprocessor saved to {preprocessor_path}")

    # (可选) 保存特征名称列表，方便后续加载模型时使用
    feature_names_path = os.path.join(MODELS_DIR, 'salary_feature_names.json')
    with open(feature_names_path, 'w', encoding='utf-8') as f:
        json.dump(feature_names, f)
    print(f"Feature names saved to {feature_names_path}")


if __name__ == '__main__':
    train_model()